import 'dart:convert';

class OrdenList {
  String? id, status, totalPrice, totalQuantity, create, statusDetail, deliveryPrice;
  String? plataform, target;
  String? operationType, paymentMethodId, paymentTypeId, statusPay, statusDetailPay, currencyId;
  String? cardLastDigits, cardname;

  OrdenList({this.id, this.status, this.deliveryPrice, this.totalPrice, this.totalQuantity, this.create, this.statusDetail, this.plataform, this.target, this.operationType, this.paymentMethodId, this.paymentTypeId, this.statusPay, this.statusDetailPay, this.currencyId, this.cardLastDigits, this.cardname});

  factory OrdenList.fromJson(Map<String, dynamic> json) => OrdenList(
        id: json["id"],
        status: json["status"],
        deliveryPrice: json["DeliveryPrice"],
        totalPrice: json["totalPrice"],
        totalQuantity: json["totalQuantity"],
        create: json["create"],
        statusDetail: json["statusDetail"],
        plataform: json["payment"]["plataform"],
        target: json["payment"]["target"],
        operationType: json["detailPayment"]["operation_type"],
        paymentMethodId: json["detailPayment"]["payment_method_id"],
        paymentTypeId: json["detailPayment"]["payment_type_id"],
        statusPay: json["detailPayment"]["status"],
        statusDetailPay: json["detailPayment"]["status_detail"],
        currencyId: json["detailPayment"]["currency_id"],
        cardLastDigits: json["detailPayment"]["card"]["last_four_digits"],
        cardname: json["detailPayment"]["card"]["cardholder"]["name"],
      );

  Map<String, dynamic> toJson() => {'id': id, 'status': status, 'DeliveryPrice': deliveryPrice, 'totalPrice': totalPrice, 'totalQuantity': totalQuantity, 'create': create, 'statusDetail': statusDetail, 'plataform': plataform, 'target': target, 'operationType': operationType, 'payment_method_id': paymentMethodId, 'paymentMethodId': paymentTypeId, 'statusPay': statusPay, 'statusDetailPay': statusDetailPay, 'currencyId': currencyId, 'cardLastDigits': cardLastDigits, 'cardname': cardname};
}

List<OrdenList> demoOrdenListlist = [
  OrdenList(
    id: "as456sa456asasadgdag23111112312",
    status: "bolsa",
    deliveryPrice: "0",
    totalPrice: "299",
    totalQuantity: "totalQuantity",
    create: "create",
    statusDetail: "statusDetail",
    plataform: "plataform",
    target: "target",
    operationType: "operation_type",
    paymentMethodId: "payment_method_id",
    paymentTypeId: "payment_type_id",
    statusPay: "statusPay",
    statusDetailPay: "status_detail",
    currencyId: "currency_id",
    cardLastDigits: "card_last_four_digits",
    cardname: "cardname",
  ),
  OrdenList(
    id: "as456sa456asasadgdag23111112312",
    status: "processing_payment",
    deliveryPrice: "0",
    totalPrice: "299",
    totalQuantity: "totalQuantity",
    create: "create",
    statusDetail: "statusDetail",
    plataform: "plataform",
    target: "target",
    operationType: "operation_type",
    paymentMethodId: "payment_method_id",
    paymentTypeId: "payment_type_id",
    statusPay: "statusPay",
    statusDetailPay: "status_detail",
    currencyId: "currency_id",
    cardLastDigits: "card_last_four_digits",
    cardname: "cardname",
  ),
  OrdenList(
    id: "as456sa456asasadgdag23111112312",
    status: "acreddit_payment",
    deliveryPrice: "0",
    totalPrice: "299",
    totalQuantity: "totalQuantity",
    create: "create",
    statusDetail: "statusDetail",
    plataform: "plataform",
    target: "target",
    operationType: "operation_type",
    paymentMethodId: "payment_method_id",
    paymentTypeId: "payment_type_id",
    statusPay: "statusPay",
    statusDetailPay: "status_detail",
    currencyId: "currency_id",
    cardLastDigits: "card_last_four_digits",
    cardname: "cardname",
  ),
  OrdenList(
    id: "as456sa456asasadgdag23111112312",
    status: "packet",
    deliveryPrice: "0",
    totalPrice: "299",
    totalQuantity: "totalQuantity",
    create: "create",
    statusDetail: "statusDetail",
    plataform: "plataform",
    target: "target",
    operationType: "operation_type",
    paymentMethodId: "payment_method_id",
    paymentTypeId: "payment_type_id",
    statusPay: "statusPay",
    statusDetailPay: "status_detail",
    currencyId: "currency_id",
    cardLastDigits: "card_last_four_digits",
    cardname: "cardname",
  ),
  OrdenList(
    id: "as456sa456asasadgdag23111112312",
    status: "shipped",
    deliveryPrice: "0",
    totalPrice: "299",
    totalQuantity: "totalQuantity",
    create: "create",
    statusDetail: "statusDetail",
    plataform: "plataform",
    target: "target",
    operationType: "operation_type",
    paymentMethodId: "payment_method_id",
    paymentTypeId: "payment_type_id",
    statusPay: "statusPay",
    statusDetailPay: "status_detail",
    currencyId: "currency_id",
    cardLastDigits: "card_last_four_digits",
    cardname: "cardname",
  ),
  OrdenList(
    id: "as456sa456asasadgdag23111112312",
    status: "finish",
    deliveryPrice: "0",
    totalPrice: "299",
    totalQuantity: "totalQuantity",
    create: "create",
    statusDetail: "statusDetail",
    plataform: "plataform",
    target: "target",
    operationType: "operation_type",
    paymentMethodId: "payment_method_id",
    paymentTypeId: "payment_type_id",
    statusPay: "statusPay",
    statusDetailPay: "status_detail",
    currencyId: "currency_id",
    cardLastDigits: "card_last_four_digits",
    cardname: "cardname",
  ),
  OrdenList(
    id: "as456sa456asasadgdag23111112312",
    status: "pendient_payment",
    deliveryPrice: "0",
    totalPrice: "299",
    totalQuantity: "totalQuantity",
    create: "create",
    statusDetail: "statusDetail",
    plataform: "plataform",
    target: "target",
    operationType: "operation_type",
    paymentMethodId: "payment_method_id",
    paymentTypeId: "payment_type_id",
    statusPay: "statusPay",
    statusDetailPay: "status_detail",
    currencyId: "currency_id",
    cardLastDigits: "card_last_four_digits",
    cardname: "cardname",
  ),
  OrdenList(
    id: "as456sa456asasadgdag23111112312",
    status: "rejected_payment",
    deliveryPrice: "0",
    totalPrice: "299",
    totalQuantity: "totalQuantity",
    create: "create",
    statusDetail: "statusDetail",
    plataform: "plataform",
    target: "target",
    operationType: "operation_type",
    paymentMethodId: "payment_method_id",
    paymentTypeId: "payment_type_id",
    statusPay: "statusPay",
    statusDetailPay: "status_detail",
    currencyId: "currency_id",
    cardLastDigits: "card_last_four_digits",
    cardname: "cardname",
  ),
  OrdenList(
    id: "as456sa456asasadgdag23111112312",
    status: "cancel",
    deliveryPrice: "0",
    totalPrice: "299",
    totalQuantity: "totalQuantity",
    create: "create",
    statusDetail: "statusDetail",
    plataform: "plataform",
    target: "target",
    operationType: "operation_type",
    paymentMethodId: "payment_method_id",
    paymentTypeId: "payment_type_id",
    statusPay: "statusPay",
    statusDetailPay: "status_detail",
    currencyId: "currency_id",
    cardLastDigits: "card_last_four_digits",
    cardname: "cardname",
  ),
];
